### ISSUE TITLE
Crash when opening game after modpack 0.4 -> 0.5 update

### ISSUE THREAD

**Issue by Pugsworth** [MSandro/sky_fabrication3#22]
I updated the pack from 0.4 to 0.5.
Now when launching, it crashes with a cryptic error. I couldn't find any specific mods to be at fault.
It almost looks like it's fabric itself.

```
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 114: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:296)
	at org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:859)
	at org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:828)
	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:782)
	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:752)
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:440)
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:479)
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1371)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_5872.&lt;clinit&gt;(class_5872.java:9)
	at net.minecraft.class_5871.method_33968(class_5871.java:16)
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at net.minecraft.class_5871.&lt;clinit&gt;(class_5871.java:12)
	at net.minecraft.class_2939.&lt;clinit&gt;(class_2939.java:33)
	at net.minecraft.class_5463.&lt;clinit&gt;(class_5463.java:19)
	at net.minecraft.class_5458.method_30572(class_5458.java:52)
	at net.minecraft.class_5458.method_30566(class_5458.java:86)
	at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
	at net.minecraft.class_5458.&lt;clinit&gt;(class_5458.java:85)
	at net.minecraft.class_2378.&lt;clinit&gt;(class_2378.java:291)
	at net.minecraft.class_2966.method_12851(class_2966.java:49)
	at net.minecraft.client.main.Main.main(Main.java:153)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
	at org.spongepowered.asm.util.asm.MixinVerifier.isAssignableFrom(MixinVerifier.java:104)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:188)
	... 39 more

```

**Comment by MSandro** [comment]
Which launcher are you using?
Maybe try to reinstall the pack.

**Comment by Pugsworth** [comment]
> Which launcher are you using? Maybe try to reinstall the pack.

I'm using GDLauncher.
I'll try to fresh install an instance of 0.5.

**Comment by MSandro** [comment]
GD Launcher caused issues for me, if u are on Linux, try PolyMC

**Comment by MSandro** [comment]
[Pugsworth](https://github.com/Pugsworth) were you able to solve your problem? If yes, please close this issue.

**Comment by Pugsworth** [comment]
I can confirm that for some reason 0.5 doesn't launch with GDLauncher.
The last time I tried PolyMC, it wasn't working well. I'll mess with some things to see what I can do.
Thank you!
