### ISSUE TITLE
I can't launch modpack

### ISSUE THREAD

**Issue by GrishaCrysta** [MSandro/sky_fabrication3#67]
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config cloth-common-events-v1.mixins.json for mod cloth-common-events-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config cloth-common-events-v1.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'cloth-common-events-v1.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by MSandro** [comment]
try to launch it a second time with the currently newest version 0.5.7a, or switch your launher, Curseforge or Prism Launcher should work well.

**Comment by MSandro** [comment]
closed because of no response since weeks.
